name: Bug report 🐛
description:
  Something not working as expected? This is the place to report your issue.
title: '[Bug]: '
labels: 'type: bug 🐛'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report.
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package(s) are you using?
      multiple: true
      options:
        - '@ed-ui/react'
        - '@ed-ui/styles'
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
  - type: input
    id: version
    attributes:
      label: Package version
      description: 'Which version(s) are you using?'
      placeholder: e.g. v10.42.0
    validations:
      required: true
  - type: input
    id: react-version
    attributes:
      label: React version
      description: 'Which React version are you using?'
      placeholder: e.g. v17.0.2
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Tell us more about the problem that you're running into"
      placeholder: What did you see? What did you expect to see?
    validations:
      required: true
  - type: input
    id: example-url
    attributes:
      label: CodeSandbox example
      description: |
        Re-create the issue using [CodeSandbox](https://codesandbox.io/). We have templates for [@ed-ui/react](),
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description:
        'How do we reproduce the error you described using the CodeSandbox link
        above?'
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/estartando-devs/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label:
            I checked the [current
            issues](https://github.com/estartando-devs/ed-ui/issues) for
            duplicate problems
