name: Storybook

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: yarn install

      - name: Build and update stories
        run: yarn deploy:storybook
