name: Storybook

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup git
        run: |
          git config --local user.email "estartandodevs@gmail.com"
          git config --local user.name "Estartando Devs"

      - name: Install Packages
        run: yarn install

      - name: Build and update stories
        run: yarn deploy:storybook
